import { Component, OnInit, AfterViewInit } from '@angular/core';
import { from } from 'rxjs';
import { Breakpoints, BreakpointObserver, BreakpointState } from '@angular/cdk/layout';

declare var $: any;
import 'jarallax';
import { map } from 'rxjs/operators';
declare var jarallax: any;

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']

})
export class DashboardComponent implements OnInit {

  items: any[];

  system: boolean = false;
  remove: boolean = true;
  mobile
  tinyMceConfig

  constructor(private breakpointObserver: BreakpointObserver) { }
  
  

configureTinyMce() {
    this.tinyMceConfig = {
      branding: false,
      height: 'calc(100vh - 132px)',
      image_advtab: true,
      imagetools_toolbar: `
        rotateleft rotateright |
        flipv fliph | 
        editimage imageoptions`,
      importcss_append: !0,
      inline: false,
      menubar: true,
      paste_data_images: !0,
      plugins: 'export pagebreak code',
      toolbar: `export pagebreak code |
        insertText |
        copy undo redo formatselect |
        bold italic strikethrough forecolor backcolor |
        link | alignleft aligncenter alignright alignjustify |
        numlist bullist outdent indent |
        removeformat`,
      setup: (editor) => {
        editor.on('init', function (e) {
        editor.setContent(`<h4>&nbsp;</h4>
<p class="MsoNormal" style="margin-left: 36.0pt;"><strong><span style="font-size: 13.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">TESTE DE DESENVOLVIMENTO DE SISTEMAS - FRONTEND</span></strong></p>
<p class="MsoNormal" style="line-height: 15.2pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt;">&nbsp;</span></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Nome Completo: Alan Gon&ccedil;alves Irala</span></strong></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Data: 13/10/2021</span></strong></p>
<p class="MsoNormal" style="line-height: 13.8pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt;">&nbsp;</span></p>
<p class="MsoNormal"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Instru&ccedil;&atilde;o Inicial</span></strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">:<strong> Favor disponibilizar a prova no GITBHUB.</strong></span></p>
<p class="MsoNormal" style="line-height: 14.0pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -18.2pt; line-height: 125%; mso-list: l3 level1 lfo1; tab-stops: 36.0pt; margin: 0cm 68.0pt .0001pt 36.0pt;"><!-- [if !supportLists]--><strong><span style="font-size: 12.0pt; line-height: 125%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span style="font-size: 12.0pt; line-height: 125%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">Nenhum corpo que n&atilde;o seja s&oacute;lido &eacute; cristal. Conclui-se logicamente que: </span><span style="font-size: 12.0pt; line-height: 125%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">(Somente uma resposta correta)</span></p>
<p class="MsoNormal" style="line-height: 3.05pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) Algum cristal n&atilde;o &eacute; corpo s&oacute;lido</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) Todo corpo s&oacute;lido &eacute; cristal</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( <span style="color: red;">X</span>) Todo cristal &eacute; corpo s&oacute;lido</span></strong></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) Nenhum corpo s&oacute;lido &eacute; cristal</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) Nenhum cristal &eacute; corpo s&oacute;lido</span></p>
<p class="MsoNormal" style="line-height: 13.8pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-indent: -18.2pt; line-height: 107%; mso-list: l3 level1 lfo1; tab-stops: 36.0pt; margin: 0cm 19.0pt .0001pt 36.0pt;"><!-- [if !supportLists]--><strong><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">A soma de dois n&uacute;meros &eacute; 16 e a diferen&ccedil;a dos seus quadrados &eacute; 128. O produto desses dois n&uacute;meros &eacute;:</span></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">(Somente uma resposta correta)</span></p>
<p class="MsoNormal" style="line-height: 9.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">()&ndash;36</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">()&ndash;12</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">()12</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">()36</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">(</span><strong><span style="font-size: 12pt; font-family: Arial, sans-serif; background: white;"><span style="color: red;">X</span></span></strong><span style="background-color: white; font-family: Arial, sans-serif; font-size: 12pt;">)48</span></p>
<p class="MsoNormal" style="line-height: 14.9pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt; text-indent: -18.2pt; line-height: 112%; mso-list: l3 level1 lfo1; tab-stops: 36.0pt;"><!-- [if !supportLists]--><strong><span style="font-size: 11.5pt; line-height: 112%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span style="font-size: 11.5pt; line-height: 112%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">Em determinada rua, h&aacute; 5 resid&ecirc;ncias que est&atilde;o numeradas em forma de progress&atilde;o geom&eacute;trica crescente, de modo que a primeira resid&ecirc;ncia recebeu numera&ccedil;&atilde;o 3, e a segunda, numera&ccedil;&atilde;o 12. Com base nessas informa&ccedil;&otilde;es, assinalar a alternativa</span></p>
<p class="MsoNormal" style="line-height: .05pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">CORRETA:</span></p>
<p class="MsoNormal" style="line-height: 1.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">(Somente uma resposta correta)</span></p>
<p class="MsoNormal" style="line-height: 9.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) A numera&ccedil;&atilde;o da terceira casa &eacute; 21.</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) A numera&ccedil;&atilde;o da quarta casa &eacute; 30.</span></p>
<p class="MsoNormal" style="margin: 0cm 8.0pt .0001pt 35.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) Somando-se a numera&ccedil;&atilde;o da primeira e da terceira casa, o resultado &eacute; o n&uacute;mero da quarta casa.</span></p>
<p class="MsoNormal" style="margin-left: 35.0pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( <span style="color: red;">X</span>) O resultado da soma da numera&ccedil;&atilde;o da terceira e da quarta casa &eacute; igual a 240.</span></strong></p>
<p class="MsoNormal" style="margin-left: 35.0pt; line-height: 98%;"><span style="font-size: 12.0pt; line-height: 98%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; background: white; mso-highlight: white;">( ) O resultado da soma da numera&ccedil;&atilde;o das cinco casas &eacute; igual a 1.025.</span></p>
<p class="MsoNormal" style="line-height: .2pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt; text-indent: -18.2pt; mso-list: l3 level1 lfo1; tab-stops: 36.0pt;"><!-- [if !supportLists]--><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Se:</span></p>
<p class="MsoNormal" style="line-height: 1.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">1=6</span></p>
<p class="MsoNormal" style="line-height: 1.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">2=26</span></p>
<p class="MsoNormal" style="line-height: 1.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">3=326</span></p>
<p class="MsoNormal" style="line-height: 1.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="line-height: 112%; margin: 0cm 412.0pt .0001pt 36.0pt;"><span style="font-size: 11.5pt; line-height: 112%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">4=4.326 5= ?</span></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Qual ser&aacute; o valor correspondente ao 5?</span></p>
<p class="MsoNormal" style="margin-left: 36.0pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; color: red;">54326</span></strong></p>
<p class="MsoNormal" style="margin-left: 36.0pt; text-indent: -18.2pt; mso-list: l0 level1 lfo2; tab-stops: 36.0pt;"><strong><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span style="font-size: 11.5pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">Considerando o c&oacute;digo JavaScript abaixo assinale a alternativa correta:</span></p>
<p class="MsoNormal" style="line-height: 17.55pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&lt;html&gt;</span></p>
<p class="MsoNormal" style="margin-left: 74.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&lt;script&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">var a = 20;</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">var b = 10;</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">document.write("Trinta &eacute; " + (a + b) + " e n&atilde;o "</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">+ (2 * a + b) + ".");</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">var minhaVariavel = new Set();</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">minhaVariavel.add(1);</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">minhaVariavel.add("some text");</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">minhaVariavel.add("foo");</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 109.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">document.write("Tamanho: " + minhaVariavel.size);</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 74.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&lt;/script&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 38.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&lt;/html&gt;</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 18.8pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: .2pt; line-height: 154%; mso-list: l2 level2 lfo3; tab-stops: 63.9pt; margin: 0cm 191.0pt .0001pt 56.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 154%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 154%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">) Trinta &eacute; 2010 e n&atilde;o 4010. Tamanho: </span></p>
<p class="MsoNormal" style="text-indent: .2pt; line-height: 154%; mso-list: l2 level2 lfo3; tab-stops: 63.9pt; margin: 0cm 191.0pt .0001pt 56.0pt;">&nbsp;</p>
<p class="MsoNormal" style="text-indent: .2pt; line-height: 154%; mso-list: l2 level2 lfo3; tab-stops: 63.9pt; margin: 0cm 191.0pt .0001pt 56.0pt;"><span style="font-size: 12.0pt; line-height: 154%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-spacerun: yes;">&nbsp;</span><strong style="mso-bidi-font-weight: normal;">( <span style="color: red;">X</span>) Trinta &eacute; 30 e n&atilde;o 50. Tamanho: 3</strong></span></p>
<p class="MsoNormal" style="line-height: .05pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 56.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) Trinta &eacute; 2010 e n&atilde;o 40 10. Tamanho: undefined</span></p>
<p class="MsoNormal" style="line-height: 7.5pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 56.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) Trinta &eacute; 30 e n&atilde;o 50. Tamanho: undefined</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span><strong style="text-indent: -18.2pt;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">6.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></strong><span style="text-indent: -18.2pt; font-size: 12pt; line-height: 150%; font-family: Arial, sans-serif; background: white;">Assinale a op&ccedil;&atilde;o que representa a tag HTML 5 respons&aacute;vel por reproduzir arquivos de contenham som ou m&uacute;sica:</span></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) &lt;phonic&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) &lt;img&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) &lt;sound&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) &lt;music&gt;</span></p>
<p class="MsoNormal" style="line-height: 7.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( <span style="color: red;">X</span>) &lt;audio&gt;</span></strong></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong><strong style="text-indent: -18.2pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">7.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></strong><span style="text-indent: -18.2pt; font-size: 12pt; font-family: Arial, sans-serif;">No desenvolvimento web, SASS &eacute; um(a):</span></p>
<p class="MsoNormal" style="line-height: 9.1pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) framework para desenvolvimento em JavaScript, compat&iacute;vel com Angular.</span></p>
<p class="MsoNormal" style="line-height: 17.55pt; mso-line-height-rule: exactly;"><!--[endif]--><a name="page3"></a></p>
<p class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">( ) framework para desenvolvimento em Ruby</span></p>
<p class="MsoNormal" style="line-height: 6.9pt; mso-line-height-rule: exactly;"><span style="font-size: 10.0pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 28.0pt; text-indent: -7.2pt; mso-list: l1 level3 lfo4; tab-stops: 28.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial; color: red;">X</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">) extens&atilde;o do CSS que permite o desenvolvimento de regras, vari&aacute;veis e mixins.</span></strong></p>
<p class="MsoNormal" style="line-height: 6.9pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 28.0pt; text-indent: -7.2pt; mso-list: l1 level3 lfo4; tab-stops: 28.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">) modelo de arquitetura do Ruby on Rails</span></p>
<p class="MsoNormal" style="line-height: 6.9pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 28.0pt; text-indent: -7.2pt; mso-list: l1 level3 lfo4; tab-stops: 28.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">) framework para desenvolvimento JSP</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 17.6pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span><strong style="text-indent: -17.8pt;"><span style="font-size: 12.0pt; line-height: 159%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">8.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></strong><span style="text-indent: -17.8pt; font-size: 12pt; line-height: 159%; font-family: Arial, sans-serif; background: white;">Em rela&ccedil;&atilde;o ao processamento do c&oacute;digo JavaScript abaixo, o valor da vari&aacute;vel b ser&aacute;: </span><span style="text-indent: -17.8pt; font-size: 12pt; line-height: 159%; font-family: Consolas;">var temp = null;</span></p>
<p class="MsoNormal" style="line-height: 5.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><span style="font-size: 12.0pt; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">var ind;</span></p>
<p class="MsoNormal" style="line-height: 101%; margin: 0cm 308.0pt .0001pt 20.0pt;"><span style="font-size: 12.0pt; line-height: 101%; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">var a = (temp == ind); var b = (temp === ind);</span></p>
<p class="MsoNormal" style="line-height: .05pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">( ) true</span></p>
<p class="MsoNormal" style="line-height: 7.45pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">(<span style="color: red;">X </span>) false</span></strong></p>
<p class="MsoNormal" style="line-height: 7.55pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">( ) null</span></p>
<p class="MsoNormal" style="line-height: 7.45pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">( ) undefined</span></p>
<p class="MsoNormal" style="line-height: 7.55pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 20.0pt;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">( ) 0</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="line-height: 19.05pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong><strong style="text-indent: -18.2pt;"><span style="font-size: 12.0pt; line-height: 125%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">9.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></strong><span style="text-indent: -18.2pt; font-size: 12pt; line-height: 125%; font-family: Arial, sans-serif; background: white;">Considerando o framewok JavaScript Angular em sua vers&atilde;o 2 ou superior, assinale a quest&atilde;o correta:</span></p>
<p class="MsoNormal" style="line-height: 18.0pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-indent: -.2pt; line-height: 110%; mso-list: l1 level3 lfo4; tab-stops: 27.3pt; margin: 0cm 76.0pt .0001pt 21.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri; color: red;">X</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) A diretiva </span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 110%; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">*ngFor</span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"> &eacute; respons&aacute;vel por realizar loops de intera&ccedil;&atilde;o entre tags e propriedades HTML.</span></strong></p>
<p class="MsoNormal" style="line-height: 4.65pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -.2pt; line-height: 110%; mso-list: l1 level3 lfo4; tab-stops: 27.3pt; margin: 0cm 40.0pt .0001pt 21.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) A diretiva </span><span style="font-size: 12.0pt; line-height: 110%; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">*ngFor</span><span style="font-size: 12.0pt; line-height: 110%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"> &eacute; respons&aacute;vel por atribuir valores as propriedades da camada de controle do Angular.</span></p>
<p class="MsoNormal" style="line-height: 4.65pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 27.0pt; text-indent: -6.2pt; mso-list: l1 level3 lfo4; tab-stops: 27.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) A diretiva </span><span style="font-size: 12.0pt; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">ng-if</span><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"> &eacute; respons&aacute;vel por realizar compara&ccedil;&otilde;es booleanas entre vari&aacute;veis.</span></p>
<p class="MsoNormal" style="line-height: 7.65pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -.2pt; line-height: 109%; mso-list: l1 level3 lfo4; tab-stops: 27.3pt; margin: 0cm 35.0pt .0001pt 21.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 109%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 109%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) O termo </span><span style="font-size: 12.0pt; line-height: 109%; font-family: Consolas; mso-fareast-font-family: Consolas; mso-bidi-font-family: Consolas;">@Component</span><span style="font-size: 12.0pt; line-height: 109%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"> representa a defini&ccedil;&atilde;o de m&eacute;todos da camada de controle do Angular.</span></p>
<p class="MsoNormal" style="line-height: 4.75pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="text-indent: -.2pt; line-height: 108%; mso-list: l1 level3 lfo4; tab-stops: 27.3pt; margin: 0cm 35.0pt .0001pt 21.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 108%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 108%; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) Por padr&atilde;o, todos os arquivos de componentes Angular est&atilde;o formatados na sintaxe JavaScript.</span></p>
<p class="MsoNormal" style="line-height: 10.0pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="line-height: 16.45pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span><strong style="text-indent: -18.2pt;"><span style="font-size: 12.0pt; line-height: 125%; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">10.<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';"> </span></span></strong><span style="text-indent: -18.2pt; font-size: 12pt; line-height: 125%; font-family: Arial, sans-serif; background: white;">O m&eacute;todo ngOnInit implementado pela interface OnInit em componentes do framework Angular &eacute; respons&aacute;vel por:</span></p>
<p class="MsoNormal" style="line-height: 3.6pt; mso-line-height-rule: exactly;"><strong><span style="font-size: 12.0pt; font-family: 'Arial','sans-serif'; mso-fareast-font-family: Arial;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin-left: 27.0pt; text-indent: -6.2pt; mso-list: l1 level3 lfo4; tab-stops: 27.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) Executar comandos no final do ciclo de vida do componente.</span></p>
<p class="MsoNormal" style="line-height: 7.55pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 27.0pt; text-indent: -6.2pt; mso-list: l1 level3 lfo4; tab-stops: 27.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) Executar comandos ao carregar a p&aacute;gina do componente.</span></p>
<p class="MsoNormal" style="line-height: 7.45pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 27.0pt; text-indent: -6.2pt; mso-list: l1 level3 lfo4; tab-stops: 27.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) Executar comandos ao destruir o componente.</span></p>
<p class="MsoNormal" style="line-height: 7.55pt; mso-line-height-rule: exactly;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: 27.0pt; text-indent: -6.2pt; mso-list: l1 level3 lfo4; tab-stops: 27.0pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;"><span style="mso-list: Ignore;">(<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">) Executar comandos em qualquer lugar do componente.</span></p>
<h4 class="MsoNormal" style="line-height: 18.1pt; mso-line-height-rule: exactly;"><!--[endif]--><a name="page4"></a></h4>
<h4 class="MsoNormal" style="margin-left: 21.0pt;"><span style="font-size: 12.0pt; font-family: 'Calibri','sans-serif'; mso-fareast-font-family: Calibri;">( <strong style="mso-bidi-font-weight: normal;"><span style="color: red;">X</span>) Executar comandos no in&iacute;cio do ciclo de vida do componente.</strong></span></h4>
<h4>&nbsp;</h4>
<h4>&nbsp;</h4>`);
        });        
      }
    };
  }

ngOnInit() {
    this.configureTinyMce();
  }
}



